#!/bin/bash

source /etc/othub/config

messages=""
dailypubs=""

check_wins() {
  NODE_STATS=$(curl -s "https://api.othub.io/otp/views/v_nodes_stats_last?api_key=$API_KEY&nodeId=$NODE_ID&timeFrame=daily")
  ATTEMPTS=$(echo "$NODE_STATS" | jq -r '.[0].pubsCommited')
  WIN=$(echo "$NODE_STATS" | jq -r '.[0].pubsCommited1stEpochOnly')
  
  NETWORKPUBS=$(curl -s "https://api.othub.io/otp/views/v_pubs_stats_last?api_key=$API_KEY" | jq -r '.[0].totalPubs')
  
  dailypubs+=" $HOSTNAME won $WIN/$ATTEMPTS attempts with $NETWORKPUBS network pubs"
}


check_error() {
  logs=$(journalctl -u otnode --since '24 hour ago' | grep 'ERROR' | wc -l)
  if [[ "$logs" -gt 0 ]]; then
    messages+="ERROR has been detected on $HOSTNAME $logs times in the last 24 hours."
  fi
}

telegram_message() {
  curl -s -X POST "https://api.telegram.org/bot$BOT_ID/sendMessage" -d "chat_id=$CHAT_ID" -d "text=$1" >/dev/null
}

check_error
check_wins

telegram_message "$messages"
telegram_message "$hourlypubs"